# My Ideal Technical Stack
# Owner: Nicolas Oudard
# Usage: docker-compose up -d

# docker-compose needed
version: '3'

# docker network should be defined
# let's start with one network "default"
networks:
  default:

services:
# Here is the postgreSQL engine exposed on 5431
  db:
    image: postgres
    restart: always
# opened port 5432 to be able to connect to the db using a postgresql client direct in a shell
# Ex: psql -p 5432 -h 127.0.0.1 -U myits-user
# Else, if the port is not opened you can use the "docker exec" command
# docker exec -it technicalstackforbtocbusiness_db_1 psql -p 5432 -h 127.0.0.1 -U myits-user
#    ports:
#      - 5432:5432
    environment:
# Use a dedicate user for this pproject with a complex password
      POSTGRES_USER: myits-user
      POSTGRES_PASSWORD: neiR3aihWae5of2iiePhi0me
# PGDATA is the volume where the postgresql data file will be stored
      PGDATA: /var/lib/postgresql/data/myitsdata
# mount posgresql volume on your own computer to persist the data
    volumes:
        - /var/lib/postgresql/data/myitsdata:/var/lib/postgresql/data/myitsdata:rw

# This is an interface to admininstrate db in your docker envirnment on port 8080
# To access it, open a browser on the url http://localhost:8080
# This is only t help developers but will not be used in MyITS project
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  swagger-editor:
    image: swaggerapi/swagger-editor
    restart: always
    ports:
      - 8002:8080
    container_name: myits-swagger-editor

# docker run -p 80:8080 -e API_URL=http://generator.swagger.io/api/swagger.json swaggerapi/swagger-ui
  swagger-ui:
    image: swaggerapi/swagger-ui
    restart: always
    ports:
      - 8003:8080
    environment:
      API_URL: http://generator.swagger.io/api/swagger.json
    container_name: myits-swagger-ui
